{% set name = "libcdms" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/UV-CDAT/libcdms/archive/v3.0.1.tar.gz
  sha256: 8b53cd7821feefa0b357ca5127d9fc6164380e51f2205e7d2c5018f71a617f91

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hdf5
    - libnetcdf
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
    - libdrs
  run:
    - hdf5
    - libnetcdf
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
    - libdrs

test:
  commands:
    - test -f $PREFIX/lib/libcdms.a

about:
  home: https://github.com/UV-CDAT/libcdms
  license: '2-Clause BSD'
  license_file: 'LICENSE'
  summary: 'Climate Data Management System library'
  description: |
      The Climate Data Management System is an object-oriented data
      management system, specialized for organizing multidimensional,
      gridded data used in climate analysis and simulation.
  dev_url: https://github.com/UV-CDAT/libcdms

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
