{% set name = "libcdms" %}
{% set version = "3.1.2" %}
{% set build = 111 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/libcdms/archive/v{{ version }}.tar.gz
  sha256: 2010ef24f8f8c14a6f997206ec342e6fed9703b81f8641d70bebc992a3855e8c

build:
  number: {{ build }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - hdf5
    - hdf5 * nompi_*
    - libnetcdf
    - libnetcdf * nompi_*
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
    - libdrs
  run:
    - hdf5
    - libnetcdf
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
    - libdrs

test:
  commands:
    - test -f $PREFIX/lib/libcdms.a

about:
  home: https://github.com/CDAT/libcdms
  license: BSD-3-Clause
  license_file: 'bsd-3-clause.txt'
  summary: 'Climate Data Management System library'
  description: |
      The Climate Data Management System is an object-oriented data
      management system, specialized for organizing multidimensional,
      gridded data used in climate analysis and simulation.
  dev_url: https://github.com/CDAT/libcdms

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - muryanto1
    - downiec
    - xylar
